/**
 * TEMPORARY MOCK DATA
 * ===================
 * These are temporary mock data functions to bypass backend API errors.
 * 
 * TODO: Remove this file once backend APIs are fixed:
 * - /api/v1/analytics/risk-dashboard
 * - /api/v1/cost-forecasting/portfolio-summary
 * - /api/v1/cost-forecasting/budget-alerts
 * 
 * @deprecated This file will be removed once backend is fixed
 */

export const mockRiskDashboard = () => {
  return Promise.resolve({
    total_projects: 45,
    high_risk_count: 8,
    medium_risk_count: 22,
    low_risk_count: 15,
    high_risk_projects: 8,
    medium_risk_projects: 22,
    low_risk_projects: 15,
    average_risk_score: 52.3,
    critical_issues: 12,
    top_risk_projects: [
      {
        id: 1,
        name: 'E-Commerce Platform Redesign',
        project_id: 'PROJ-001',
        risk_score: 85.5,
        risk_level: 'High',
        project_manager: 'John Smith',
        budget_usd: 850000,
        team_size: 12,
      },
      {
        id: 2,
        name: 'Mobile Banking App',
        project_id: 'PROJ-002',
        risk_score: 78.2,
        risk_level: 'High',
        project_manager: 'Sarah Johnson',
        budget_usd: 650000,
        team_size: 8,
      },
      {
        id: 3,
        name: 'Cloud Migration Initiative',
        project_id: 'PROJ-003',
        risk_score: 72.8,
        risk_level: 'High',
        project_manager: 'Mike Chen',
        budget_usd: 1200000,
        team_size: 15,
      },
      {
        id: 4,
        name: 'CRM System Integration',
        project_id: 'PROJ-004',
        risk_score: 68.5,
        risk_level: 'Medium',
        project_manager: 'Emily Davis',
        budget_usd: 450000,
        team_size: 10,
      },
      {
        id: 5,
        name: 'Data Analytics Platform',
        project_id: 'PROJ-005',
        risk_score: 65.3,
        risk_level: 'Medium',
        project_manager: 'David Wilson',
        budget_usd: 750000,
        team_size: 11,
      },
    ],
    projects: [
      {
        project_id: 1,
        overall_risk: 85.5,
        schedule_risk: 82.0,
        budget_risk: 88.5,
        quality_risk: 75.0,
        resource_risk: 90.2,
        technical_risk: 80.5,
        last_updated: '2025-10-11T10:00:00Z',
      },
      {
        project_id: 2,
        overall_risk: 78.2,
        schedule_risk: 75.0,
        budget_risk: 82.0,
        quality_risk: 70.0,
        resource_risk: 85.0,
        technical_risk: 78.0,
        last_updated: '2025-10-11T10:00:00Z',
      },
    ],
  })
}

export const mockCostPortfolioSummary = () => {
  return Promise.resolve({
    total_projects: 45,
    total_budget: 15750000,
    total_spent: 9250000,
    total_projected: 11800000,
    budget_utilization: 58.7,
    projects_at_risk: 12,
    projects_on_track: 28,
    projects_under_budget: 5,
    average_burn_rate: 125000,
    summary: {
      total_budget: 15750000,
      total_current_spend: 9250000,
      total_projected_spend: 11800000,
      avg_budget_utilization: 58.7,
      projects_over_budget: 12,
      projects_on_track: 28,
      projects_under_budget: 5,
      total_expected_overrun: 450000,
      portfolio_health: 'Warning',
    },
    projects: [
      {
        project_id: 1,
        project_name: 'E-Commerce Platform Redesign',
        budget: 850000,
        current_spend: 725000,
        projected_spend: 920000,
        utilization: 85.3,
        overrun_risk: 0.75,
        status: 'At Risk',
      },
      {
        project_id: 2,
        project_name: 'Mobile Banking App',
        budget: 650000,
        current_spend: 380000,
        projected_spend: 645000,
        utilization: 58.5,
        overrun_risk: 0.15,
        status: 'On Track',
      },
    ],
    trends: {
      monthly_spend: [
        { month: 'May', spend: 850000 },
        { month: 'Jun', spend: 920000 },
        { month: 'Jul', spend: 1050000 },
        { month: 'Aug', spend: 1150000 },
        { month: 'Sep', spend: 1200000 },
        { month: 'Oct', spend: 1250000 },
      ],
    },
    optimization_stats: {
      projects_analyzed: 45,
      database_queries_saved: 150,
      response_time_ms: 45,
    },
  })
}

export const mockBudgetAlerts = () => {
  return Promise.resolve({
    total_alerts: 12,
    critical_alerts: 3,
    high_alerts: 5,
    medium_alerts: 4,
    alerts: [
      {
        project_id: 1,
        project_identifier: 'PROJ-001',
        project_name: 'E-Commerce Platform Redesign',
        total_budget: 850000,
        current_spend: 725000,
        budget_utilization: 85.3,
        overrun_probability: 0.75,
        expected_overrun_amount: 70000,
        risk_level: 'critical',
        alert_severity: 'critical',
        days_remaining: 45,
        burn_rate: 12500,
        projected_final_cost: 920000,
      },
      {
        project_id: 2,
        project_identifier: 'PROJ-002',
        project_name: 'Mobile Banking App',
        total_budget: 650000,
        current_spend: 520000,
        budget_utilization: 80.0,
        overrun_probability: 0.65,
        expected_overrun_amount: 45000,
        risk_level: 'high',
        alert_severity: 'high',
        days_remaining: 60,
        burn_rate: 8500,
        projected_final_cost: 695000,
      },
      {
        project_id: 3,
        project_identifier: 'PROJ-003',
        project_name: 'Cloud Migration Initiative',
        total_budget: 1200000,
        current_spend: 950000,
        budget_utilization: 79.2,
        overrun_probability: 0.70,
        expected_overrun_amount: 85000,
        risk_level: 'critical',
        alert_severity: 'critical',
        days_remaining: 30,
        burn_rate: 18000,
        projected_final_cost: 1285000,
      },
      {
        project_id: 4,
        project_identifier: 'PROJ-004',
        project_name: 'CRM System Integration',
        total_budget: 450000,
        current_spend: 315000,
        budget_utilization: 70.0,
        overrun_probability: 0.55,
        expected_overrun_amount: 25000,
        risk_level: 'high',
        alert_severity: 'high',
        days_remaining: 75,
        burn_rate: 5500,
        projected_final_cost: 475000,
      },
      {
        project_id: 5,
        project_identifier: 'PROJ-005',
        project_name: 'Data Analytics Platform',
        total_budget: 750000,
        current_spend: 525000,
        budget_utilization: 70.0,
        overrun_probability: 0.60,
        expected_overrun_amount: 40000,
        risk_level: 'high',
        alert_severity: 'high',
        days_remaining: 90,
        burn_rate: 7500,
        projected_final_cost: 790000,
      },
      {
        project_id: 6,
        project_identifier: 'PROJ-006',
        project_name: 'Security Enhancement Project',
        total_budget: 380000,
        current_spend: 250000,
        budget_utilization: 65.8,
        overrun_probability: 0.48,
        expected_overrun_amount: 18000,
        risk_level: 'medium',
        alert_severity: 'medium',
        days_remaining: 120,
        burn_rate: 3500,
        projected_final_cost: 398000,
      },
      {
        project_id: 7,
        project_identifier: 'PROJ-007',
        project_name: 'Customer Portal Upgrade',
        total_budget: 520000,
        current_spend: 380000,
        budget_utilization: 73.1,
        overrun_probability: 0.58,
        expected_overrun_amount: 30000,
        risk_level: 'high',
        alert_severity: 'high',
        days_remaining: 50,
        burn_rate: 8000,
        projected_final_cost: 550000,
      },
      {
        project_id: 8,
        project_identifier: 'PROJ-008',
        project_name: 'API Gateway Implementation',
        total_budget: 420000,
        current_spend: 290000,
        budget_utilization: 69.0,
        overrun_probability: 0.52,
        expected_overrun_amount: 22000,
        risk_level: 'medium',
        alert_severity: 'medium',
        days_remaining: 85,
        burn_rate: 4500,
        projected_final_cost: 442000,
      },
      {
        project_id: 9,
        project_identifier: 'PROJ-009',
        project_name: 'Microservices Refactoring',
        total_budget: 680000,
        current_spend: 545000,
        budget_utilization: 80.1,
        overrun_probability: 0.68,
        expected_overrun_amount: 52000,
        risk_level: 'critical',
        alert_severity: 'critical',
        days_remaining: 40,
        burn_rate: 14000,
        projected_final_cost: 732000,
      },
      {
        project_id: 10,
        project_identifier: 'PROJ-010',
        project_name: 'DevOps Pipeline Automation',
        total_budget: 350000,
        current_spend: 225000,
        budget_utilization: 64.3,
        overrun_probability: 0.45,
        expected_overrun_amount: 15000,
        risk_level: 'medium',
        alert_severity: 'medium',
        days_remaining: 100,
        burn_rate: 3000,
        projected_final_cost: 365000,
      },
      {
        project_id: 11,
        project_identifier: 'PROJ-011',
        project_name: 'AI Chatbot Integration',
        total_budget: 480000,
        current_spend: 355000,
        budget_utilization: 74.0,
        overrun_probability: 0.62,
        expected_overrun_amount: 35000,
        risk_level: 'high',
        alert_severity: 'high',
        days_remaining: 65,
        burn_rate: 6500,
        projected_final_cost: 515000,
      },
      {
        project_id: 12,
        project_identifier: 'PROJ-012',
        project_name: 'Legacy System Modernization',
        total_budget: 920000,
        current_spend: 685000,
        budget_utilization: 74.5,
        overrun_probability: 0.63,
        expected_overrun_amount: 58000,
        risk_level: 'medium',
        alert_severity: 'medium',
        days_remaining: 70,
        burn_rate: 11000,
        projected_final_cost: 978000,
      },
    ],
    optimization_stats: {
      projects_analyzed: 45,
      database_queries_saved: 180,
      response_time_ms: 38,
    },
  })
}
